/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import juego_multihilos.JugadorDos;
import juego_multihilos.JugadorUno;
import juego_multihilos.MaquinaDos;
import juego_multihilos.MaquinaUno;

/**
 *
 * @author Jimmy
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    JugadorUno j1;
    JugadorDos j2;

    MaquinaUno m1;
    MaquinaDos m2;

    boolean aleatorio1 = false;
    boolean aleatorio2 = false;

    boolean aleatorio3 = false;
    boolean aleatorio4 = false;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Black Jack 21");
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCartaJudadorUno1 = new javax.swing.JLabel();
        BtnIniciarJuego = new javax.swing.JButton();
        BtnEscogerJ1 = new javax.swing.JButton();
        lblCartaJudadorDos1 = new javax.swing.JLabel();
        lblCartaMaquinaUno = new javax.swing.JLabel();
        lblCartaMaquinaDos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("21");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel2.setText("BlackJack");

        lblCartaJudadorUno1.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        lblCartaJudadorUno1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCartaJudadorUno1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cartas/12.png"))); // NOI18N
        lblCartaJudadorUno1.setBorder(new javax.swing.border.MatteBorder(null));

        BtnIniciarJuego.setBackground(new java.awt.Color(0, 0, 0));
        BtnIniciarJuego.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        BtnIniciarJuego.setForeground(new java.awt.Color(255, 51, 51));
        BtnIniciarJuego.setText("START");
        BtnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarJuegoActionPerformed(evt);
            }
        });

        BtnEscogerJ1.setBackground(new java.awt.Color(51, 204, 0));
        BtnEscogerJ1.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        BtnEscogerJ1.setForeground(new java.awt.Color(255, 255, 255));
        BtnEscogerJ1.setText("ELEGIR");
        BtnEscogerJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEscogerJ1ActionPerformed(evt);
            }
        });

        lblCartaJudadorDos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cartas/2.png"))); // NOI18N

        lblCartaMaquinaUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cartas/13.png"))); // NOI18N

        lblCartaMaquinaDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cartas/8.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Engravers MT", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("MAQUINA");

        jLabel4.setFont(new java.awt.Font("Engravers MT", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("JUGADOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCartaJudadorUno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCartaJudadorDos1)
                        .addGap(102, 102, 102)
                        .addComponent(lblCartaMaquinaUno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCartaMaquinaDos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(BtnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(BtnEscogerJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(653, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCartaJudadorUno1)
                        .addComponent(lblCartaJudadorDos1)
                        .addComponent(lblCartaMaquinaUno))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCartaMaquinaDos)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addComponent(BtnEscogerJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(jLabel4)
                    .addContainerGap(384, Short.MAX_VALUE)))
        );

        lblCartaMaquinaDos.getAccessibleContext().setAccessibleName("lblCartaMaquinaDos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarJuegoActionPerformed
        // TODO add your handling code here:
        int MilisegundosJugador = 700;
        int MilisegundosMaquina = 30;

        j1 = new JugadorUno(MilisegundosJugador);
        j2 = new JugadorDos(MilisegundosJugador);

        m1 = new MaquinaUno(MilisegundosMaquina);
        m2 = new MaquinaDos(MilisegundosMaquina);

        aleatorio1 = false;
        aleatorio2 = false;

        aleatorio3 = false;
        aleatorio4 = false;

        BtnIniciarJuego.setEnabled(false);

        j1.start();
        j2.start();

        m1.start();
        m2.start();

    }//GEN-LAST:event_BtnIniciarJuegoActionPerformed

    private void BtnEscogerJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEscogerJ1ActionPerformed
        // TODO add your handling code here:
        j1.stop();
        j2.stop();
        aleatorio1 = true;
        aleatorio2 = true;

        m1.stop();
        m2.stop();
        aleatorio3 = true;
        aleatorio4 = true;

        sumarCartas();
    }//GEN-LAST:event_BtnEscogerJ1ActionPerformed

    private void sumarCartas() {

        if (JugadorUno.JugCarta1 + JugadorDos.JugCarta2 <= 21) {
            if (MaquinaUno.MaqCarta1 + MaquinaDos.MaqCarta2 <= 21) {
                if (JugadorUno.JugCarta1 + JugadorDos.JugCarta2 > MaquinaUno.MaqCarta1 + MaquinaDos.MaqCarta2) {
                    JOptionPane.showMessageDialog(null, "GANASTE");
                } else {
                    JOptionPane.showMessageDialog(null, "PERDISTE");
                }
            } else {
                JOptionPane.showMessageDialog(null, "GANASTE");
            }
        } else {
            JOptionPane.showMessageDialog(null, "PERDISTE");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEscogerJ1;
    private javax.swing.JButton BtnIniciarJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel lblCartaJudadorDos1;
    public static javax.swing.JLabel lblCartaJudadorUno1;
    public static javax.swing.JLabel lblCartaMaquinaDos;
    public static javax.swing.JLabel lblCartaMaquinaUno;
    // End of variables declaration//GEN-END:variables

}
